Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true

### devsecops-vm  #### 
  config.vm.define "devsecops-vm" do |devsecops_vm|
    devsecops_vm.vm.box = "bento/fedora-40"
    devsecops_vm.vm.hostname = "devsecops-vm"
    devsecops_vm.vm.network "public_network", ip: "192.168.10.35", mac: "000c29cc83b2"
    devsecops_vm.vm.disk :disk, size: "20GB", primary: true
    devsecops_vm.vm.provision "shell", path: "install-script.sh.fedora"  
    devsecops_vm.vm.provider "vmware_desktop" do |vmw|
      vmw.memory = "8192"
      vmw.cpus = "4"
    end
  end
end