VAGRANT_API_VERSION = "2"
Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true

  ### devsecops-vm  #### 
  config.vm.define "devsecops-vm" do |devsecops_vm|
    devsecops_vm.vm.box = "bento/fedora-40"
    devsecops_vm.vm.hostname = "devsecops-vm"
    devsecops_vm.vm.network "public_network", ip: "192.168.10.53"
    devsecops_vm.vm.disk :disk, size: "20GB", primary: true
    devsecops_vm.vm.provision "shell", 
      path: "install-script.sh.fedora",
      privileged: true,
      keep_color: true

    devsecops_vm.vm.provider "vmware_desktop" do |vmw|
      vmw.memory = "8192"
      vmw.cpus = "4"
      # Configure vmx settings
      vmw.linked_clone = true
      vmw.vmx["displayname"] = "devsecops-vm"
      vmw.vmx["memsize"] = "8192"
      vmw.vmx["numvcpus"] = "4"
      vmw.vmx["ethernet1.address"] = "AA:BB:CC:DD:EE:00"
      vmw.vmx["ethernet1.addresstype"] = "static"
      
    end
  end
end
